import type { ResourceCost } from '../types/resources';

export const BALANCE = {
  townHall: {
    hp: 1500,
    x: 12,
    y: 32,
  },
  spire: {
    hp: 4500,
    x: 52,
    y: 32,
    spawnCooldown: 25,
  },
  buildings: {
    WarriorGuild: { hp: 600, cost: { gold: 120, wood: 20, stone: 0 } as ResourceCost },
    RangerLodge: { hp: 500, cost: { gold: 100, wood: 30, stone: 0 } as ResourceCost },
    ZeeyaShrine: { hp: 550, cost: { gold: 140, wood: 10, stone: 20 } as ResourceCost },
    Market: { hp: 450, cost: { gold: 150, wood: 40, stone: 10 } as ResourceCost },
    Blacksmith: { hp: 500, cost: { gold: 180, wood: 20, stone: 40 } as ResourceCost },
    GuardTower: { hp: 400, cost: { gold: 90, wood: 15, stone: 25 } as ResourceCost },
    LumberMill: { hp: 350, cost: { gold: 60, wood: 30, stone: 0 } as ResourceCost },
    Quarry: { hp: 350, cost: { gold: 80, wood: 20, stone: 0 } as ResourceCost },
    Farm: { hp: 300, cost: { gold: 50, wood: 20, stone: 0 } as ResourceCost },
    ManaWell: { hp: 350, cost: { gold: 120, wood: 10, stone: 50 } as ResourceCost },
    Warehouse: { hp: 400, cost: { gold: 100, wood: 40, stone: 40 } as ResourceCost },
    Housing: { hp: 350, cost: { gold: 70, wood: 30, stone: 10 } as ResourceCost },
    HuntersLodge: { hp: 300, cost: { gold: 60, wood: 20, stone: 0 } as ResourceCost },
    Armory: { hp: 500, cost: { gold: 160, wood: 20, stone: 30 } as ResourceCost },
    EnchantersTower: { hp: 450, cost: { gold: 200, wood: 10, stone: 0 } as ResourceCost },
    AdventurersGuild: { hp: 400, cost: { gold: 140, wood: 20, stone: 10 } as ResourceCost },
    Embassy: { hp: 400, cost: { gold: 180, wood: 0, stone: 30 } as ResourceCost },
  },
  resourceProduction: {
    LumberMill: { wood: 8 },
    Quarry: { stone: 6 },
    Farm: { food: 10 },
    ManaWell: { mana: 5 },
    HuntersLodge: { food: 6 },
    Market: { gold: 45 },
    TownHall: { gold: 35 },
  },
  resourceConsumption: {
    Housing: { food: 2 },
  },
  storageCap: {
    Warehouse: 200,
    base: { gold: 9999, wood: 500, stone: 500, food: 500, mana: 200, population: 10 },
  },
  housingPop: 5,
  heroUpkeep: { food: 0.8 },
  spells: {
    rallySpark: { cost: 80, manaCost: 10, maxCooldown: 15, radius: 6 },
    zeeyaMend: { cost: 100, manaCost: 15, maxCooldown: 18, radius: 6, healAmount: 75 },
    astryxFlare: { cost: 150, manaCost: 25, maxCooldown: 25, radius: 10, damage: 45 },
    diplomaticEnvoy: { cost: 60, manaCost: 10, maxCooldown: 20 },
    dungeonReveal: { cost: 80, manaCost: 15, maxCooldown: 25 },
    massRally: { cost: 200, manaCost: 30, maxCooldown: 40, radius: 999 },
  },
  combat: {
    heroShareRate: 0.7,
    monsterBaseDefense: 5,
    lairDefenseAttack: 8,
    spireDefenseAttack: 25,
    heroRegenResting: 0.12,
    heroRegenPassive: 2,
    heroFleeThreshold: 0.3,
    levelUpHpBonus: 30,
    levelUpAttackBonus: 5,
    levelUpDefenseBonus: 3,
    xpPerKill: 25,
    goldPerKill: 15,
    xpPerHeal: 10,
    guardTowerDamage: 12,
    guardTowerDefense: 2,
  },
  threat: {
    baseIncrease: 0.6,
    earlyGameCap: 0.03,
    spireStirEveryDays: 10,
    spireStirThreatBonus: 5,
  },
  raidWarningDistance: 18,
  logTrimLimit: 500,
  heroLevelCap: 10,
  kynmarkedChance: 0.12,
  kynmarkedHpMultiplier: 1.3,
  kynmarkedAtkMultiplier: 1.3,
  kynmarkedCourageBonus: 25,
  squadMaxSize: 4,
  squadMinSize: 2,
  squadBonusPerExtraMember: 0.10,
  specializationUnlockLevel: 5,
  ultimateUnlockLevel: 8,
  sovereignFavorRegenPerTick: 0.1,
  sovereignFavorRegenPerDay: 5,
  sovereignFavorStart: 50,
  sovereignFavorMax: 100,
  botDecisionInterval: 24,
  startingResources: {
    easy: { gold: 550, wood: 100, stone: 80, food: 100, mana: 30, population: 3 },
    standard: { gold: 440, wood: 60, stone: 50, food: 60, mana: 20, population: 2 },
    hard: { gold: 385, wood: 30, stone: 25, food: 30, mana: 10, population: 1 },
    brutal: { gold: 330, wood: 20, stone: 15, food: 20, mana: 5, population: 1 },
  },
  equipment: {
    baseDropChance: 0.05,
    bossDropChance: 1.0,
    rarityWeights: { common: 50, uncommon: 30, rare: 15, epic: 4, legendary: 1 },
    shopRestockInterval: 5,
    shopInventorySize: 6,
  },
  dungeons: {
    minRooms: 5,
    maxRooms: 15,
    expeditionSpeed: 1,
    revivePenaltyHp: 0.5,
    cooldownAfterClear: 10,
  },
  diplomacy: {
    standingDecayPerDay: 1,
    giftMinCost: 50,
    giftMaxCost: 200,
    tradeAgreementDuration: 30,
    allianceDuration: 60,
    questInterval: 10,
    questExpiry: 20,
  },
  skills: {
    skillPointsPerLevel: 1,
    ultimateUnlockLevel: 8,
    ultimateCooldown: 60,
  },
  rivals: {
    decisionInterval: 24,
    startingDistance: 0.5,
  },
} as const;
